<div id="modalCookies" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" style="height: 90%; width: 80%;">
    <div class="modal-content" style="height: 100%; width: 80%;">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h3 id="myModalLabel" style="text-align: center;">POLITICA DE COOKIES</h3>
      </div>
      <div class="modal-body">
        <p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			<span id="docs-internal-guid-8d4f7b45-6277-68b9-c03b-1953a9266cc8"><span style="font-size: 14.6667px; font-family: Calibri; vertical-align: baseline; white-space: pre-wrap;">Utilizamos cookies propias y de terceros para optimizar tu experiencia de navegaci&oacute;n y servicio en nuestra p&aacute;gina web. Recuerda que puedes rechazarlas o cambiar su configuraci&oacute;n siguiendo las instrucciones que puedes leer a continuaci&oacute;n. , pero ten en cuenta que el acceso, uso y, en general, la navegaci&oacute;n por el sitio web de Aula Tem&aacute;tica (Animad Versi&oacute;n, S.L.) suponen el consentimiento del usuario a la utilizaci&oacute;n de cookies por parte de Aula Tem&aacute;tica y/o de sus proveedores de servicios.</span></span></p>
		<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			<span id="docs-internal-guid-8d4f7b45-6277-68b9-c03b-1953a9266cc8"><span style="font-size: 14.6667px; font-family: Calibri; vertical-align: baseline; white-space: pre-wrap;">Puedes obtener informaci&oacute;n ampliada sobre las cookies y su uso en la web www.aboutcookies.org, pero a continuaci&oacute;n te resumimos sus principales caracter&iacute;sticas, qu&eacute; tipos de cookies utiliza Aula Tem&aacute;tica &nbsp;y c&oacute;mo puedes desactivarlas en tu navegador:</span></span></p>
		<div dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			&nbsp;</div>
		<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			<span id="docs-internal-guid-8d4f7b45-6277-68b9-c03b-1953a9266cc8"><span style="font-size: 14.6667px; font-family: Calibri; font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">&iquest;Qu&eacute; son las cookies y para qu&eacute; se utilizan?</span></span></p>
		<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			<span id="docs-internal-guid-8d4f7b45-6277-68b9-c03b-1953a9266cc8"><span style="font-size: 14.6667px; font-family: Calibri; vertical-align: baseline; white-space: pre-wrap;">Una cookie es un fichero que se descarga en su ordenador al acceder a determinadas p&aacute;ginas web. Las cookies permiten a una p&aacute;gina web, entre otras cosas, almacenar y recuperar informaci&oacute;n sobre los h&aacute;bitos de navegaci&oacute;n de un usuario o de su equipo, incluyendo informaci&oacute;n estad&iacute;stica an&oacute;nima y, dependiendo de la informaci&oacute;n que contengan y de la forma en que utilice su equipo, pueden utilizarse para reconocer al usuario.</span></span></p>
		<div dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			&nbsp;</div>
		<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			<span id="docs-internal-guid-8d4f7b45-6277-68b9-c03b-1953a9266cc8"><span style="font-size: 14.6667px; font-family: Calibri; font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">Tipos de cookies que utiliza Aula Tem&aacute;tica</span></span></p>
		<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			<span id="docs-internal-guid-8d4f7b45-6277-68b9-c03b-1953a9266cc8"><span style="font-size: 14.6667px; font-family: Calibri; vertical-align: baseline; white-space: pre-wrap;">&bull; Cookies de sesi&oacute;n: Mantienen al usuario identificado ante el sitio web, permitiendo su interacci&oacute;n con el mismo.</span></span></p>
		<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			<span id="docs-internal-guid-8d4f7b45-6277-68b9-c03b-1953a9266cc8"><span style="font-size: 14.6667px; font-family: Calibri; vertical-align: baseline; white-space: pre-wrap;">&bull; Cookies de an&aacute;lisis: Son aqu&eacute;llas que bien tratadas por nosotros o por terceros, nos permiten cuantificar el n&uacute;mero de usuarios y as&iacute; realizar la medici&oacute;n y an&aacute;lisis estad&iacute;stico de la utilizaci&oacute;n que hacen los usuarios del servicio ofertado. Asimismo, se almacena informaci&oacute;n como el idioma, ciudad a la que est&aacute; asignada la direcci&oacute;n IP desde la que acceden los usuarios, frecuencia de las visitas, tiempo de visita, tipo de terminal desde el que se realiza la visita y/o productos m&aacute;s visitados, entre otros. Para ello se analiza su navegaci&oacute;n en nuestra p&aacute;gina web con el fin de mejorar su experiencia, as&iacute; como la oferta de productos o servicios que le ofrecemos.</span></span></p>
		<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			<span id="docs-internal-guid-8d4f7b45-6277-68b9-c03b-1953a9266cc8"><span style="font-size: 14.6667px; font-family: Calibri; vertical-align: baseline; white-space: pre-wrap;">&bull; Cookies de navegaci&oacute;n: Estas cookies recogen informaci&oacute;n sobre el uso que las visitas hacen de la web, por ejemplo p&aacute;ginas vistas, errores de carga&hellip; Es informaci&oacute;n gen&eacute;rica y an&oacute;nima, donde no se incluyen datos personales, ni se recoge informaci&oacute;n que identifique a los visitantes; siendo el objetivo &uacute;ltimo mejorar el funcionamiento de la web.</span></span></p>
		<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			<span id="docs-internal-guid-8d4f7b45-6277-68b9-c03b-1953a9266cc8"><span style="font-size: 14.6667px; font-family: Calibri; vertical-align: baseline; white-space: pre-wrap;">&bull; Cookies publicitarias: Son aqu&eacute;llas que, bien tratadas por nosotros o por terceros, nos permiten gestionar de la forma m&aacute;s eficaz posible la eventual oferta de los espacios publicitarios que hubiera en la p&aacute;gina web, adecuando el contenido del anuncio al contenido del servicio solicitado o al uso que realice de nuestra p&aacute;gina web. Para ello podemos analizar sus h&aacute;bitos de navegaci&oacute;n en Internet y podemos mostrarle publicidad relacionada con su perfil de navegaci&oacute;n.</span></span></p>
		<div dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			&nbsp;</div>
		<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			<span id="docs-internal-guid-8d4f7b45-6277-68b9-c03b-1953a9266cc8"><span style="font-size: 14.6667px; font-family: Calibri; vertical-align: baseline; white-space: pre-wrap;">Adicionalmente, algunos servicios de Aula Tem&aacute;tica pueden utilizar conectores con diversas redes sociales como Facebook, Twitter, Google +, etc. Al utilizar este sitio web y en caso de acceder a los servicios de Aula Tem&aacute;tica a trav&eacute;s de las mismas, est&aacute;s autorizando a dichas redes sociales a almacenar una cookie con tus preferencias de navegaci&oacute;n. Recuerda que la referida cookie puede ser eliminada, y que puedes anular los permisos de acceso de Aula Tem&aacute;tica desde la configuraci&oacute;n de privacidad de cada red social en cuesti&oacute;n.</span></span></p>
		<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			<span id="docs-internal-guid-8d4f7b45-6277-68b9-c03b-1953a9266cc8"><span style="font-size: 14.6667px; font-family: Calibri; vertical-align: baseline; white-space: pre-wrap;">Te informamos de que algunas de las cookies empleadas han sido desarrolladas por terceros, y que los mismos podr&iacute;an utilizar estos datos para mejorar sus propios servicios y/o para ofrecerlos a los usuarios.</span></span></p>
		<div dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			&nbsp;</div>
		<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			<span id="docs-internal-guid-8d4f7b45-6277-68b9-c03b-1953a9266cc8"><span style="font-size: 14.6667px; font-family: Calibri; font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">C&oacute;mo administrar las cookies</span></span></p>
		<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			<span id="docs-internal-guid-8d4f7b45-6277-68b9-c03b-1953a9266cc8"><span style="font-size: 14.6667px; font-family: Calibri; vertical-align: baseline; white-space: pre-wrap;">Recuerda que al visitar nuestro sitio web sin modificar la configuraci&oacute;n de tu navegador, aceptas expresamente el uso de las cookies en las condiciones establecidas en la presente pol&iacute;tica de cookies.</span></span></p>
		<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			<span id="docs-internal-guid-8d4f7b45-6277-68b9-c03b-1953a9266cc8"><span style="font-size: 14.6667px; font-family: Calibri; vertical-align: baseline; white-space: pre-wrap;">No obstante, dado que las cookies no son estrictamente necesarias para el uso de nuestro sitio web, te recordamos que puedes permitir, bloquear o eliminar las cookies instaladas en tu equipo mediante la configuraci&oacute;n de las opciones del navegador instalado en su ordenador. En la funci&oacute;n &ldquo;Ayuda&rdquo; de la mayor&iacute;a de los navegadores se indica c&oacute;mo configurar tu navegador para que no acepte cookies, para que te notifique cada vez que reciba una nueva cookie, as&iacute; como para desactivar completamente todas las cookies. Adem&aacute;s, puedes deshabilitar o eliminar datos similares utilizados por las extensiones (add-on) de los navegadores, como las &ldquo;Flash Cookies&rdquo;, cambiando la configuraci&oacute;n de dichas extensiones o visitando el sitio web del fabricante. &Uacute;nicamente te pedimos que tengas en mente que si rechazas el uso de cookies algunos de los servicios del sitio web ser&aacute;n autom&aacute;ticamente restringidos.</span></span></p>
		<div dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			&nbsp;</div>
		<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			<span id="docs-internal-guid-8d4f7b45-6277-68b9-c03b-1953a9266cc8"><span style="font-size: 14.6667px; font-family: Calibri; font-weight: 700; vertical-align: baseline; white-space: pre-wrap;">Actualizaci&oacute;n de la pol&iacute;tica de cookies</span></span></p>
		<p dir="ltr" style="line-height:1.3800000000000001;margin-top:0pt;margin-bottom:10pt;text-align: justify;">
			<span id="docs-internal-guid-8d4f7b45-6277-68b9-c03b-1953a9266cc8"><span style="font-size: 14.6667px; font-family: Calibri; vertical-align: baseline; white-space: pre-wrap;">Aula Tem&aacute;tica se reserva el derecho a modificar su Pol&iacute;tica de Privacidad incluyendo expresamente la Pol&iacute;tica de Cookies en cualquier momento a su entera discreci&oacute;n. Cualquier modificaci&oacute;n de la misma ser&aacute; debidamente publicada en el sitio web.</span></span></p>
		<div>
			&nbsp;</div>
      </div>
    </div>
  </div>
</div>
